### ISSUE TITLE
How to configure the client side

### ISSUE THREAD

**Issue by Chenhb123** [tenclass/clink#1]
I have learned a lot from your project, and thank you very much for your open source。

Because I have just been exposed to the topic of remote CUDA, and I have some questions about the client side of the project. I look forward to receiving your reply：

1. How should I understand fake cuda dlls?  And where should I obtain fake cuda dlls
2. What does execute file refer to and how should I start the client
3. About Build Environment，What does "sdk19041" represent and where should it be obtained from

Above, look forward to your reply very much. Thanks
Also, Do you have any plans to implement clients on Linux ?

**Comment by andystime** [comment]
> I have learned a lot from your project, and thank you very much for your open source。
> 
> Because I have just been exposed to the topic of remote CUDA, and I have some questions about the client side of the project. I look forward to receiving your reply：
> 
> 1. How should I understand fake cuda dlls?  And where should I obtain fake cuda dlls
> 2. What does execute file refer to and how should I start the client
> 3. About Build Environment，What does "sdk19041" represent and where should it be obtained from
> 
> Above, look forward to your reply very much. Thanks Also, Do you have any plans to implement clients on Linux ?

Thanks for your attention.
1. The fake cuda dlls means the dlls built from source which were used to supply cuda drvier api instead of real nvidia cuda dlls. When you build client side, you will get two dlls named nvcuda.dll and nvapi64.dll. For windows applications using cuda driver api, they would load these dlls to get GPU support.
2. This project provides a method for hijacking the official NVIDIA CUDA driver API. You can build the executable file yourself, or you can find other programs that utilize the CUDA driver API, such as Cinema 4D's OC-Render.
3. "sdk19041" is a sdk number for windows api, you can get more information at https://developer.microsoft.com.
4. The plan for Linux may be postponed due to work-related reasons.
